;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-forward
        c-indent-line-or-region
        comment-dwim-line
        crux-duplicate-and-comment-current-line-or-region
        downcase-region
        easy-kill
        keyboard-quit
        kill-region
        sp-backward-sexp
        sp-delete-char
        sp-forward-sexp
        sp-remove-active-pair-overlay
        sp-splice-sexp
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        crux-recentf-ido-find-file
        crux-switch-to-previous-buffer
        god-local-mode
        ido-switch-buffer
        yank-rectangle
        ))
